import Head from "next/head";

export default function ProjectsPage() {
	return (
		<>
			<Head>
				<title>project | rizkyemha.dev</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='flex flex-col space-y-8'>
				<h1>Projects</h1>
			</div>
		</>
	);
}
